version: '3.8'

services:
  # PostgreSQL数据库 (生产环境)
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recruitment_db
      POSTGRES_USER: recruitment_user
      POSTGRES_PASSWORD: recruitment_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - recruitment_network

  # Redis缓存 (用于匹配结果缓存)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - recruitment_network

  # Django后端
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://recruitment_user:recruitment_pass@db:5432/recruitment_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - recruitment_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # React前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - recruitment_network

  # Nginx反向代理 (生产环境)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static:/var/www/static
    depends_on:
      - backend
      - frontend
    networks:
      - recruitment_network

volumes:
  postgres_data:

networks:
  recruitment_network:
    driver: bridge