# Generated by Django 5.2.4 on 2025-09-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('matching', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingjob',
            name='target_students',
            field=models.ManyToManyField(blank=True, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='skillmatchdetail',
            name='match_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='matching.matchresult'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='recommended_jobs',
            field=models.ManyToManyField(through='matching.RecommendationItem', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.studentrecommendation'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['student', '-overall_score'], name='matching_ma_student_b35ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['job', '-overall_score'], name='matching_ma_job_id_9fb3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['overall_score'], name='matching_ma_overall_30d8e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('student', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendationitem',
            unique_together={('recommendation', 'job')},
        ),
    ]
