# Generated by Django 5.2.4 on 2025-09-29 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, max_length=2000)),
                ('custom_resume', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('interview_scheduled', '面试安排'), ('interview_completed', '面试完成'), ('offer_made', '发出录用'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('employer_notes', models.TextField(blank=True, max_length=1000)),
                ('rejection_reason', models.TextField(blank=True, max_length=500)),
                ('match_score', models.FloatField(blank=True, help_text='AI匹配分数 (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('skill_match_details', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('interview_scheduled', '面试安排'), ('interview_completed', '面试完成'), ('offer_made', '发出录用'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('interview_scheduled', '面试安排'), ('interview_completed', '面试完成'), ('offer_made', '发出录用'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], max_length=20)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('student_to_employer', '学生对雇主'), ('employer_to_student', '雇主对学生'), ('interview_feedback', '面试反馈'), ('application_feedback', '申请反馈')], max_length=30)),
                ('rating', models.IntegerField(help_text='评分 1-5 星', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=1000)),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('process_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', '电话面试'), ('video', '视频面试'), ('on_site', '现场面试'), ('technical', '技术面试'), ('hr', 'HR面试'), ('final', '终面')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True)),
                ('interviewer_notes', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('scheduled', '已安排'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('rescheduled', '已重新安排')], default='scheduled', max_length=20)),
                ('technical_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('communication_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cultural_fit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般'), ('poor', '较差')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
