# Generated by Django 5.2.4 on 2025-09-29 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('requirements', models.TextField(max_length=2000)),
                ('responsibilities', models.TextField(max_length=2000)),
                ('job_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('internship', '实习'), ('contract', '合同工'), ('freelance', '自由职业')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', '入门级'), ('junior', '初级'), ('mid', '中级'), ('senior', '高级'), ('lead', '领导级'), ('executive', '管理层')], max_length=20)),
                ('remote_option', models.CharField(choices=[('on_site', '现场办公'), ('remote', '远程办公'), ('hybrid', '混合办公')], default='on_site', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='CNY', max_length=10)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(default='中国', max_length=100)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_applications', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('job_types', models.JSONField(blank=True, default=list)),
                ('experience_levels', models.JSONField(blank=True, default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('remote_options', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('immediate', '立即'), ('daily', '每日'), ('weekly', '每周')], default='daily', max_length=20)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobSkillPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.FloatField(default=0.5, help_text='额外加分 (0.1-2.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)])),
            ],
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('critical', '关键'), ('important', '重要'), ('nice_to_have', '加分项')], default='important', max_length=20)),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('weight', models.FloatField(default=1.0, help_text='匹配算法中的权重 (0.1-5.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]
