# Generated by Django 5.2.4 on 2025-09-29 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('education', models.TextField(verbose_name='教育背景')),
                ('experience', models.TextField(verbose_name='工作经验')),
                ('skills', models.TextField(verbose_name='技能特长')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历文件')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-created_at'],
            },
        ),
    ]
